insert into productos (id, nombre) values (1, 'Mushrooms - Honey');
insert into productos (id, nombre) values (2, 'Butter Balls Salted');
insert into productos (id, nombre) values (3, 'Longos - Chicken Curried');
insert into productos (id, nombre) values (4, 'Squid - Tubes / Tenticles 10/20');
insert into productos (id, nombre) values (5, 'Jerusalem Artichoke');
insert into productos (id, nombre) values (6, 'Gelatine Leaves - Envelopes');
insert into productos (id, nombre) values (7, 'Yokaline');
insert into productos (id, nombre) values (8, 'Mix - Cappucino Cocktail');
insert into productos (id, nombre) values (9, 'Sauce - Vodka Blush');
insert into productos (id, nombre) values (10, 'Oranges - Navel, 72');
insert into productos (id, nombre) values (11, 'Rambutan');
insert into productos (id, nombre) values (12, 'Long Island Ice Tea');
insert into productos (id, nombre) values (13, 'Mikes Hard Lemonade');
insert into productos (id, nombre) values (14, 'Bread - Sour Batard');
insert into productos (id, nombre) values (15, 'Sausage - Blood Pudding');
insert into productos (id, nombre) values (16, 'Salami - Genova');
insert into productos (id, nombre) values (17, 'Wine - Barossa Valley Estate');
insert into productos (id, nombre) values (18, 'Radish');
insert into productos (id, nombre) values (19, 'Oil - Hazelnut');
insert into productos (id, nombre) values (20, 'Island Oasis - Banana Daiquiri');
